### ISSUE TITLE
Swift 3 ?

### ISSUE THREAD

**Issue by kraymond70** [allenwong/30DaysofSwift#47]
Hi, I juste started learning Swift and I wonder if you are using Swift 3 or not.
Your experience should be a great start point for me.
Thxs

**Comment by sarossell** [comment]
I tried to learn Swift 3, but my programing background dating back to the
early 80s just got in the way of comprehending modern object-oriented
programming (OOP) methods. The syntax is not impossible to learn. In fact,
the language seems very well designed and intelligent. The problem for me
lies in the implementation of the concept in the first place. What I mean
is, OOP is by it's very nature lazy. Relying on an IDE to continually
retype ridiculously long variable names and having to devote literally
paragraphs of code to achieve some of the simplest operations is just
unacceptable to me.

It also doesn't help that the language is very new and is still growing and
changing. The changes from version to version have been painful in spite of
being necessary and beneficial. Such is the nature of growth. And as far as
programming languages go, you could do far, far worse.

My advice: If you're going to learn Swift, start at version 3 with some
up-to-date training materials. They may not yet exist, to be honest.
Version 3 was only just released a week or so ago. And the differences
between version 2.3 and 3.0 are big enough to make you want to tear your
hair out.

Best of luck!


On Saturday, July 30, 2016 at T16:02:26Z, Raymond Kpatchaa (
notifications@github.com) wrote:

Hi, I juste started learning Swift and I wonder if you are using Swift 3 or
not.
Your experience should be a great start point for me.
Thxs

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/allenwong/30DaysofSwift/issues/47>, or mute the thread

**Comment by kraymond70** [comment]
Thank you for this quick reply.

I am going to read Apple's Swift 3 book and I hope to find some tutorials that should cover the new version.
Thank you also for the great job you've done so far.

Regards.

**Comment by allenwong** [comment]
I will find some free time to update all the projects with Swift 3. Now busy working on my new app.😭

**Comment by RishabhTayal** [comment]
@allenwong can you please create a new branch named `swift-3` so we can work on it and create a PR.

**Comment by RishabhTayal** [comment]
#48 Here is a WIP

**Comment by allenwong** [comment]
Here it is, guys!!!
https://github.com/allenwong/30DaysofSwift/tree/Swift-3
Thanks a ton!!!

**Comment by RishabhTayal** [comment]
Created a PR for this: https://github.com/allenwong/30DaysofSwift/pull/50
